#/bin/bash
cat recordsdc/oai_zaguan.unizar.es_10515.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_10569.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_12083.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_12579.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_12916.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_13609.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_31437.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_31445.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_31531.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_47560.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_47565.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_48506.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_48511.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_48525.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_48573.xml | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_4969.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_5621.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_60513.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_60514.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_61116.xml | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_61209.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_61953.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_64179.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_64283.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_6476.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_6491.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_65350.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_65396.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_65439.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_6780.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_69800.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_69844.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_69849.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_69862.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_76507.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_77602.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_77796.xml | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_78610.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_84004.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_85000.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_85660.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_86859.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_8770.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_8807.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_89074.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_9224.xml  | grep "Javier|javier" >> Javiers.txt
cat recordsdc/oai_zaguan.unizar.es_9274.xml  | grep "Javier|javier" >> Javiers.txt


